name: main

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  OPAMROOT: /home/charlie/.opam
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:

  compile-and-run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/easycrypt/ec-build-box
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install jasmin
        run: opam install jasmin.2024.07.0

      - name: compile and run
        run: opam exec -- make compile_and_run

  check-all:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/easycrypt/ec-build-box
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install easycrypt
        run: |
          opam pin add -n easycrypt https://github.com/EasyCrypt/easycrypt.git#r2024.01
          opam install easycrypt
      - name: detect SMT solvers
        run: opam exec -- easycrypt why3config

      - name: check all
        run: ECARGS=-script TIMEOUT=60 opam exec -- make check_all

